let heros = [
    "Homem de Ferro",
  "Capitão América",
  "Thor",
  "Hulk",
  "Viúva Negra",
  "Gavião Arqueiro",
  "Homem Aranha",
  "Pantera Negra",
  "Doutor Estranho",
  "Feiticeira Escarlate",
  "Visão",
  "Falcão",
  "Máquina de Combate",
  "Gamora",
  "Nebulosa",
  "Star-Lord",
  "Rocket Raccoon",
  "Groot",
  "Drax",
  "Mantis",
  "Mercúrio",
  "Vampira",
  "Ciclope",
  "Tempestade",
  "Wolverine"
]